# This runs the drift check every day at 3:00 AM

schedules:
- cron: "0 8 * * *"
  displayName: 'Daily drift detection'
  branches:
    includes:
    - main
    - develope
    exclude:
      readme

# Its automatically triger PR on manin and Dev branch

trigger:
  branches:
    includes:
      - main
      - develope

# Define the variables like subscriptions

variables:
  azureSubscription: ''  # replace with services connection for subscription
  #acrName: '' # replace with acr name
  azureServiceConnection: ''
  terraformVersion: '1.7.0'
  groups: 'terraform-secrets'

# in this stage terraform code will validate

stages:
- stage: validate
  jobs:
  - job: terraform_validate
    pool:
    - vmImage: 'agent-pool'
    steps:
    - task: TerraformInstaller@1
      inputs:
       terraformVersion: $(terraformVersion)
    - Script: |
        chmod +x validate_all.sh
        ./validate_all.sh
    displayName: 'Run Multi-Env Vallidation Script'

# in this stage will initialize the remote state file on the storage account
# this will once validation completed

- stage: Deploy_Dev
  DependsOn: validate
  condition: suceeded() 
  jobs:
  - deployment: Deploy_Dev
    environment: 'developement' # Points to Azure DevOps Environment for tracking
    pool:
    - vmImage: 'agent-pool'
    stratergy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformTaskV4@4
            displayName: 'terraform init (Dev)'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(system.DefaultWorkingDirectory)/environments/dev'
              backendServiceARM: $(azureServiceConnection)
              backendAzureRMResourceGroupname: ''
              backendAzureRMStorageAccountName: 'stterraformstateprimary'
              backendAzureRMContainerName: 'dev-tfstate'
              backendAzureRMKey: 'dev_terraform.tfstate'

# in this stage first task initial the backend again  
# second task will run the terraform plan and output will save in the  tfplan file
# Third task will save the plan file to the artifact directory


- stage: Dev_deployment
  jobs: 
  - job: Terraform_plan
    displayName: 'Terraform_plan_(Dev)'
    pool: {vmImage: 'agent-pool'}
    steps:
    - checkout: self
    - task: TerraformTaskV4@4
      inputs: 
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(system.DefaultWorkingDirectory)/environments/dev'
        backendServiceARM: $(azureServiceConnection)
        backendAzureRMResourceGroupname: ''
        backendAzureRMStorageAccountName: 'stterraformstateprimary'
        backendAzureRMContainerName: 'dev-tfstate'
        backendAzureRMKey: 'dev_terraform.tfstate'

    - task: TerraformTaskV4
      inputs: 
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(system.DefaultWorkingDirectory)/environments/dev'
        environmentServiceConnection: $(azureServiceConnection)
        # We save the plan output to a file
        commandOptions: '-var-file="terraform.tfvars -out=dev.tfplan'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(system.DefaultWorkingDirectory)/environments/dev/dev.tfplan'
        artifact: 'dev.tfplan'
  stages:
- stage: Create_PR
  displayName: 'Auto Create Pull Request'
  jobs:
  - job: Create_PR_Job
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - checkout: self
      persistCredentials: true # Allows the agent to use the system token for Git commands

    - script: |
        # 1. Set Auth Header for Azure DevOps CLI
        export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
        
        # 2. Define Variables
        SOURCE_BRANCH=$(Build.SourceBranchName)
        TARGET_BRANCH="main" # Or "dev", etc.
        TITLE="Auto-PR: Merging $SOURCE_BRANCH into $TARGET_BRANCH"
        
        # 3. Check if a PR already exists to prevent duplicate errors
        EXISTING_PR=$(az repos pr list --source-branch $SOURCE_BRANCH --target-branch $TARGET_BRANCH --status active --query "[].pullRequestId" -o tsv)

        if [ -z "$EXISTING_PR" ]; then
          echo "🚀 No active PR found. Creating new Pull Request..."
          az repos pr create \
            --source-branch $SOURCE_BRANCH \
            --target-branch $TARGET_BRANCH \
            --title "$TITLE" \
            --description "This PR was automatically generated by the CI pipeline after successful validation." \
            --status active
        else
          echo "ℹ️  Active PR already exists (ID: $EXISTING_PR). Skipping creation."
        fi
      displayName: 'Run az repos pr create'
      env:
        # This is a built-in variable that gives the CLI permission to act on your behalf
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)      

  # In this Job will apply the terraform code and provisioned the resources to azure
  
  # This step will download the artifact (tfplan) file from the artifact directory which created by the plan task 
  #  first task initial the backend again    
  # Second task will run the terraform apply and provisioned the resources to the azure

  - job: Terraform_Apply
    displayName: 'Terraform_Apply (dev)'
    DependsOn: Terraform_plan
    # This prevents the apply from running if the plan failed
    condition: suceeded()
    pool: {vmImage: 'agent-pool'}
    stratergy:
      runOnce:
      deploy:
        steps:
        - download: current
          artifact: 'dev-plan'

        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$system.DefaultWorkingDirectory/environments/dev'  
            backendServiceARM: $(azureServiceConnection)
            backendAzureRMResourceGroupname: ''
            backendAzureRMStorageAccountName: 'stterraformstateprimary'
            backendAzureRMContainerName: 'dev-tfstate'
            backendAzureRMKey: 'dev_terraform.tfstate'

        - task: TerraforTaskV4@4
          displayName: 'Apply saved plan'
          inputs:
            provider:
            command: 'apply'
            workingDirectory: '$system.DefaultWorkingDirectory/environments/dev'
            environmentServiceConnection: $(azureServiceConnection)
            # We use the plan file instead of variables here
            commandOptions: '$(Pipeline.Workspace)/dev/plan/dev.tfplan'







                


  


    






        
